/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOrganizationRouteImport } from './routes/verify-organization'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ApprovalRequiredRouteImport } from './routes/approval-required'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as FeedbackProgrammeRouteImport } from './routes/feedback.$programme'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardSurveysIndexRouteImport } from './routes/dashboard/surveys/index'
import { Route as DashboardStakeholdersIndexRouteImport } from './routes/dashboard/stakeholders/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardReportingIndexRouteImport } from './routes/dashboard/reporting/index'
import { Route as DashboardRapidEnquiryIndexRouteImport } from './routes/dashboard/rapid-enquiry/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/dashboard/notifications/index'
import { Route as DashboardFeedbackIndexRouteImport } from './routes/dashboard/feedback/index'
import { Route as DashboardDocumentsIndexRouteImport } from './routes/dashboard/documents/index'
import { Route as DashboardDocsIndexRouteImport } from './routes/dashboard/docs/index'
import { Route as DashboardCommunitySessionsIndexRouteImport } from './routes/dashboard/community-sessions/index'
import { Route as DashboardAnnouncementsIndexRouteImport } from './routes/dashboard/announcements/index'
import { Route as DashboardAccountsIndexRouteImport } from './routes/dashboard/accounts/index'
import { Route as DashboardSurveysThankYouRouteImport } from './routes/dashboard/surveys/thank-you'
import { Route as DashboardSurveysTakeSurveyRouteImport } from './routes/dashboard/surveys/take-survey'
import { Route as DashboardSurveysReviewSurveyRouteImport } from './routes/dashboard/surveys/review-survey'
import { Route as DashboardSurveysReportFormsRouteImport } from './routes/dashboard/surveys/report-forms'
import { Route as DashboardSurveysAddNewRouteImport } from './routes/dashboard/surveys/add-new'
import { Route as DashboardSurveysViewIdRouteImport } from './routes/dashboard/surveys/$view-id'
import { Route as DashboardStakeholdersAddNewRouteImport } from './routes/dashboard/stakeholders/add-new'
import { Route as DashboardStakeholdersViewIdRouteImport } from './routes/dashboard/stakeholders/$view-id'
import { Route as DashboardStakeholdersEditIdRouteImport } from './routes/dashboard/stakeholders/$edit-id'
import { Route as DashboardSettingsAddRoleRouteImport } from './routes/dashboard/settings/add-role'
import { Route as DashboardReportingReviewReportRouteImport } from './routes/dashboard/reporting/review-report'
import { Route as DashboardReportingMakeReportRouteImport } from './routes/dashboard/reporting/make-report'
import { Route as DashboardRapidEnquiryAddNewRouteImport } from './routes/dashboard/rapid-enquiry/add-new'
import { Route as DashboardRapidEnquiryEditIdRouteImport } from './routes/dashboard/rapid-enquiry/$edit-id'
import { Route as DashboardProjectsAddNewRouteImport } from './routes/dashboard/projects/add-new'
import { Route as DashboardProjectsViewIdRouteImport } from './routes/dashboard/projects/$view-id'
import { Route as DashboardFeedbackAddNewRouteImport } from './routes/dashboard/feedback/add-new'
import { Route as DashboardCommunitySessionsAddNewRouteImport } from './routes/dashboard/community-sessions/add-new'
import { Route as DashboardCommunitySessionsSessionIdRouteImport } from './routes/dashboard/community-sessions/$sessionId'
import { Route as DashboardAnnouncementsAddNewRouteImport } from './routes/dashboard/announcements/add-new'
import { Route as DashboardAnnouncementsEditIdRouteImport } from './routes/dashboard/announcements/$edit-id'
import { Route as DashboardAccountsStakeholdersRouteImport } from './routes/dashboard/accounts/stakeholders'
import { Route as DashboardAccountsRichMembersRouteImport } from './routes/dashboard/accounts/rich-members'
import { Route as DashboardAccountsHealthServiceProvidersRouteImport } from './routes/dashboard/accounts/health-service-providers'
import { Route as DashboardAccountsCommunityMembersRouteImport } from './routes/dashboard/accounts/community-members'
import { Route as DashboardAccountsAddNewRouteImport } from './routes/dashboard/accounts/add-new'
import { Route as DashboardSurveysTakeSurveyAnswerRouteImport } from './routes/dashboard/surveys/take.$survey-answer'
import { Route as DashboardSurveysEditEditIdRouteImport } from './routes/dashboard/surveys/edit.$edit-id'
import { Route as DashboardSurveysAnswerSurveyAnswerRouteImport } from './routes/dashboard/surveys/answer.$survey-answer'
import { Route as DashboardSurveysAnalyticsSurveyIdRouteImport } from './routes/dashboard/surveys/analytics.$survey-id'
import { Route as DashboardSettingsEditRoleRoleIdRouteImport } from './routes/dashboard/settings/edit-role.$roleId'
import { Route as DashboardFeedbackEditEditIdRouteImport } from './routes/dashboard/feedback/edit.$edit-id'

const VerifyOrganizationRoute = VerifyOrganizationRouteImport.update({
  id: '/verify-organization',
  path: '/verify-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRequiredRoute = ApprovalRequiredRouteImport.update({
  id: '/approval-required',
  path: '/approval-required',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const FeedbackProgrammeRoute = FeedbackProgrammeRouteImport.update({
  id: '/feedback/$programme',
  path: '/feedback/$programme',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSurveysIndexRoute = DashboardSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStakeholdersIndexRoute =
  DashboardStakeholdersIndexRouteImport.update({
    id: '/stakeholders/',
    path: '/stakeholders/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportingIndexRoute = DashboardReportingIndexRouteImport.update({
  id: '/reporting/',
  path: '/reporting/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRapidEnquiryIndexRoute =
  DashboardRapidEnquiryIndexRouteImport.update({
    id: '/rapid-enquiry/',
    path: '/rapid-enquiry/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFeedbackIndexRoute = DashboardFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentsIndexRoute = DashboardDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocsIndexRoute = DashboardDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommunitySessionsIndexRoute =
  DashboardCommunitySessionsIndexRouteImport.update({
    id: '/community-sessions/',
    path: '/community-sessions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAnnouncementsIndexRoute =
  DashboardAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsIndexRoute = DashboardAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSurveysThankYouRoute =
  DashboardSurveysThankYouRouteImport.update({
    id: '/surveys/thank-you',
    path: '/surveys/thank-you',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSurveysTakeSurveyRoute =
  DashboardSurveysTakeSurveyRouteImport.update({
    id: '/surveys/take-survey',
    path: '/surveys/take-survey',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSurveysReviewSurveyRoute =
  DashboardSurveysReviewSurveyRouteImport.update({
    id: '/surveys/review-survey',
    path: '/surveys/review-survey',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSurveysReportFormsRoute =
  DashboardSurveysReportFormsRouteImport.update({
    id: '/surveys/report-forms',
    path: '/surveys/report-forms',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSurveysAddNewRoute = DashboardSurveysAddNewRouteImport.update({
  id: '/surveys/add-new',
  path: '/surveys/add-new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSurveysViewIdRoute = DashboardSurveysViewIdRouteImport.update({
  id: '/surveys/$view-id',
  path: '/surveys/$view-id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStakeholdersAddNewRoute =
  DashboardStakeholdersAddNewRouteImport.update({
    id: '/stakeholders/add-new',
    path: '/stakeholders/add-new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStakeholdersViewIdRoute =
  DashboardStakeholdersViewIdRouteImport.update({
    id: '/stakeholders/$view-id',
    path: '/stakeholders/$view-id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStakeholdersEditIdRoute =
  DashboardStakeholdersEditIdRouteImport.update({
    id: '/stakeholders/$edit-id',
    path: '/stakeholders/$edit-id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAddRoleRoute =
  DashboardSettingsAddRoleRouteImport.update({
    id: '/settings/add-role',
    path: '/settings/add-role',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReportingReviewReportRoute =
  DashboardReportingReviewReportRouteImport.update({
    id: '/reporting/review-report',
    path: '/reporting/review-report',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReportingMakeReportRoute =
  DashboardReportingMakeReportRouteImport.update({
    id: '/reporting/make-report',
    path: '/reporting/make-report',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRapidEnquiryAddNewRoute =
  DashboardRapidEnquiryAddNewRouteImport.update({
    id: '/rapid-enquiry/add-new',
    path: '/rapid-enquiry/add-new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRapidEnquiryEditIdRoute =
  DashboardRapidEnquiryEditIdRouteImport.update({
    id: '/rapid-enquiry/$edit-id',
    path: '/rapid-enquiry/$edit-id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsAddNewRoute = DashboardProjectsAddNewRouteImport.update({
  id: '/projects/add-new',
  path: '/projects/add-new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsViewIdRoute = DashboardProjectsViewIdRouteImport.update({
  id: '/projects/$view-id',
  path: '/projects/$view-id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFeedbackAddNewRoute = DashboardFeedbackAddNewRouteImport.update({
  id: '/feedback/add-new',
  path: '/feedback/add-new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommunitySessionsAddNewRoute =
  DashboardCommunitySessionsAddNewRouteImport.update({
    id: '/community-sessions/add-new',
    path: '/community-sessions/add-new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCommunitySessionsSessionIdRoute =
  DashboardCommunitySessionsSessionIdRouteImport.update({
    id: '/community-sessions/$sessionId',
    path: '/community-sessions/$sessionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAnnouncementsAddNewRoute =
  DashboardAnnouncementsAddNewRouteImport.update({
    id: '/announcements/add-new',
    path: '/announcements/add-new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAnnouncementsEditIdRoute =
  DashboardAnnouncementsEditIdRouteImport.update({
    id: '/announcements/$edit-id',
    path: '/announcements/$edit-id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsStakeholdersRoute =
  DashboardAccountsStakeholdersRouteImport.update({
    id: '/accounts/stakeholders',
    path: '/accounts/stakeholders',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsRichMembersRoute =
  DashboardAccountsRichMembersRouteImport.update({
    id: '/accounts/rich-members',
    path: '/accounts/rich-members',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsHealthServiceProvidersRoute =
  DashboardAccountsHealthServiceProvidersRouteImport.update({
    id: '/accounts/health-service-providers',
    path: '/accounts/health-service-providers',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsCommunityMembersRoute =
  DashboardAccountsCommunityMembersRouteImport.update({
    id: '/accounts/community-members',
    path: '/accounts/community-members',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountsAddNewRoute = DashboardAccountsAddNewRouteImport.update({
  id: '/accounts/add-new',
  path: '/accounts/add-new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSurveysTakeSurveyAnswerRoute =
  DashboardSurveysTakeSurveyAnswerRouteImport.update({
    id: '/surveys/take/$survey-answer',
    path: '/surveys/take/$survey-answer',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSurveysEditEditIdRoute =
  DashboardSurveysEditEditIdRouteImport.update({
    id: '/surveys/edit/$edit-id',
    path: '/surveys/edit/$edit-id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSurveysAnswerSurveyAnswerRoute =
  DashboardSurveysAnswerSurveyAnswerRouteImport.update({
    id: '/surveys/answer/$survey-answer',
    path: '/surveys/answer/$survey-answer',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSurveysAnalyticsSurveyIdRoute =
  DashboardSurveysAnalyticsSurveyIdRouteImport.update({
    id: '/surveys/analytics/$survey-id',
    path: '/surveys/analytics/$survey-id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsEditRoleRoleIdRoute =
  DashboardSettingsEditRoleRoleIdRouteImport.update({
    id: '/settings/edit-role/$roleId',
    path: '/settings/edit-role/$roleId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFeedbackEditEditIdRoute =
  DashboardFeedbackEditEditIdRouteImport.update({
    id: '/feedback/edit/$edit-id',
    path: '/feedback/edit/$edit-id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/approval-required': typeof ApprovalRequiredRoute
  '/error': typeof ErrorRoute
  '/verify-organization': typeof VerifyOrganizationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/feedback/$programme': typeof FeedbackProgrammeRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/dashboard/accounts/add-new': typeof DashboardAccountsAddNewRoute
  '/dashboard/accounts/community-members': typeof DashboardAccountsCommunityMembersRoute
  '/dashboard/accounts/health-service-providers': typeof DashboardAccountsHealthServiceProvidersRoute
  '/dashboard/accounts/rich-members': typeof DashboardAccountsRichMembersRoute
  '/dashboard/accounts/stakeholders': typeof DashboardAccountsStakeholdersRoute
  '/dashboard/announcements/$edit-id': typeof DashboardAnnouncementsEditIdRoute
  '/dashboard/announcements/add-new': typeof DashboardAnnouncementsAddNewRoute
  '/dashboard/community-sessions/$sessionId': typeof DashboardCommunitySessionsSessionIdRoute
  '/dashboard/community-sessions/add-new': typeof DashboardCommunitySessionsAddNewRoute
  '/dashboard/feedback/add-new': typeof DashboardFeedbackAddNewRoute
  '/dashboard/projects/$view-id': typeof DashboardProjectsViewIdRoute
  '/dashboard/projects/add-new': typeof DashboardProjectsAddNewRoute
  '/dashboard/rapid-enquiry/$edit-id': typeof DashboardRapidEnquiryEditIdRoute
  '/dashboard/rapid-enquiry/add-new': typeof DashboardRapidEnquiryAddNewRoute
  '/dashboard/reporting/make-report': typeof DashboardReportingMakeReportRoute
  '/dashboard/reporting/review-report': typeof DashboardReportingReviewReportRoute
  '/dashboard/settings/add-role': typeof DashboardSettingsAddRoleRoute
  '/dashboard/stakeholders/$edit-id': typeof DashboardStakeholdersEditIdRoute
  '/dashboard/stakeholders/$view-id': typeof DashboardStakeholdersViewIdRoute
  '/dashboard/stakeholders/add-new': typeof DashboardStakeholdersAddNewRoute
  '/dashboard/surveys/$view-id': typeof DashboardSurveysViewIdRoute
  '/dashboard/surveys/add-new': typeof DashboardSurveysAddNewRoute
  '/dashboard/surveys/report-forms': typeof DashboardSurveysReportFormsRoute
  '/dashboard/surveys/review-survey': typeof DashboardSurveysReviewSurveyRoute
  '/dashboard/surveys/take-survey': typeof DashboardSurveysTakeSurveyRoute
  '/dashboard/surveys/thank-you': typeof DashboardSurveysThankYouRoute
  '/dashboard/accounts': typeof DashboardAccountsIndexRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsIndexRoute
  '/dashboard/community-sessions': typeof DashboardCommunitySessionsIndexRoute
  '/dashboard/docs': typeof DashboardDocsIndexRoute
  '/dashboard/documents': typeof DashboardDocumentsIndexRoute
  '/dashboard/feedback': typeof DashboardFeedbackIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/rapid-enquiry': typeof DashboardRapidEnquiryIndexRoute
  '/dashboard/reporting': typeof DashboardReportingIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/stakeholders': typeof DashboardStakeholdersIndexRoute
  '/dashboard/surveys': typeof DashboardSurveysIndexRoute
  '/dashboard/feedback/edit/$edit-id': typeof DashboardFeedbackEditEditIdRoute
  '/dashboard/settings/edit-role/$roleId': typeof DashboardSettingsEditRoleRoleIdRoute
  '/dashboard/surveys/analytics/$survey-id': typeof DashboardSurveysAnalyticsSurveyIdRoute
  '/dashboard/surveys/answer/$survey-answer': typeof DashboardSurveysAnswerSurveyAnswerRoute
  '/dashboard/surveys/edit/$edit-id': typeof DashboardSurveysEditEditIdRoute
  '/dashboard/surveys/take/$survey-answer': typeof DashboardSurveysTakeSurveyAnswerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/approval-required': typeof ApprovalRequiredRoute
  '/error': typeof ErrorRoute
  '/verify-organization': typeof VerifyOrganizationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/feedback/$programme': typeof FeedbackProgrammeRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/posts': typeof PostsIndexRoute
  '/dashboard/accounts/add-new': typeof DashboardAccountsAddNewRoute
  '/dashboard/accounts/community-members': typeof DashboardAccountsCommunityMembersRoute
  '/dashboard/accounts/health-service-providers': typeof DashboardAccountsHealthServiceProvidersRoute
  '/dashboard/accounts/rich-members': typeof DashboardAccountsRichMembersRoute
  '/dashboard/accounts/stakeholders': typeof DashboardAccountsStakeholdersRoute
  '/dashboard/announcements/$edit-id': typeof DashboardAnnouncementsEditIdRoute
  '/dashboard/announcements/add-new': typeof DashboardAnnouncementsAddNewRoute
  '/dashboard/community-sessions/$sessionId': typeof DashboardCommunitySessionsSessionIdRoute
  '/dashboard/community-sessions/add-new': typeof DashboardCommunitySessionsAddNewRoute
  '/dashboard/feedback/add-new': typeof DashboardFeedbackAddNewRoute
  '/dashboard/projects/$view-id': typeof DashboardProjectsViewIdRoute
  '/dashboard/projects/add-new': typeof DashboardProjectsAddNewRoute
  '/dashboard/rapid-enquiry/$edit-id': typeof DashboardRapidEnquiryEditIdRoute
  '/dashboard/rapid-enquiry/add-new': typeof DashboardRapidEnquiryAddNewRoute
  '/dashboard/reporting/make-report': typeof DashboardReportingMakeReportRoute
  '/dashboard/reporting/review-report': typeof DashboardReportingReviewReportRoute
  '/dashboard/settings/add-role': typeof DashboardSettingsAddRoleRoute
  '/dashboard/stakeholders/$edit-id': typeof DashboardStakeholdersEditIdRoute
  '/dashboard/stakeholders/$view-id': typeof DashboardStakeholdersViewIdRoute
  '/dashboard/stakeholders/add-new': typeof DashboardStakeholdersAddNewRoute
  '/dashboard/surveys/$view-id': typeof DashboardSurveysViewIdRoute
  '/dashboard/surveys/add-new': typeof DashboardSurveysAddNewRoute
  '/dashboard/surveys/report-forms': typeof DashboardSurveysReportFormsRoute
  '/dashboard/surveys/review-survey': typeof DashboardSurveysReviewSurveyRoute
  '/dashboard/surveys/take-survey': typeof DashboardSurveysTakeSurveyRoute
  '/dashboard/surveys/thank-you': typeof DashboardSurveysThankYouRoute
  '/dashboard/accounts': typeof DashboardAccountsIndexRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsIndexRoute
  '/dashboard/community-sessions': typeof DashboardCommunitySessionsIndexRoute
  '/dashboard/docs': typeof DashboardDocsIndexRoute
  '/dashboard/documents': typeof DashboardDocumentsIndexRoute
  '/dashboard/feedback': typeof DashboardFeedbackIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/rapid-enquiry': typeof DashboardRapidEnquiryIndexRoute
  '/dashboard/reporting': typeof DashboardReportingIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/stakeholders': typeof DashboardStakeholdersIndexRoute
  '/dashboard/surveys': typeof DashboardSurveysIndexRoute
  '/dashboard/feedback/edit/$edit-id': typeof DashboardFeedbackEditEditIdRoute
  '/dashboard/settings/edit-role/$roleId': typeof DashboardSettingsEditRoleRoleIdRoute
  '/dashboard/surveys/analytics/$survey-id': typeof DashboardSurveysAnalyticsSurveyIdRoute
  '/dashboard/surveys/answer/$survey-answer': typeof DashboardSurveysAnswerSurveyAnswerRoute
  '/dashboard/surveys/edit/$edit-id': typeof DashboardSurveysEditEditIdRoute
  '/dashboard/surveys/take/$survey-answer': typeof DashboardSurveysTakeSurveyAnswerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/approval-required': typeof ApprovalRequiredRoute
  '/error': typeof ErrorRoute
  '/verify-organization': typeof VerifyOrganizationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/feedback/$programme': typeof FeedbackProgrammeRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/dashboard/accounts/add-new': typeof DashboardAccountsAddNewRoute
  '/dashboard/accounts/community-members': typeof DashboardAccountsCommunityMembersRoute
  '/dashboard/accounts/health-service-providers': typeof DashboardAccountsHealthServiceProvidersRoute
  '/dashboard/accounts/rich-members': typeof DashboardAccountsRichMembersRoute
  '/dashboard/accounts/stakeholders': typeof DashboardAccountsStakeholdersRoute
  '/dashboard/announcements/$edit-id': typeof DashboardAnnouncementsEditIdRoute
  '/dashboard/announcements/add-new': typeof DashboardAnnouncementsAddNewRoute
  '/dashboard/community-sessions/$sessionId': typeof DashboardCommunitySessionsSessionIdRoute
  '/dashboard/community-sessions/add-new': typeof DashboardCommunitySessionsAddNewRoute
  '/dashboard/feedback/add-new': typeof DashboardFeedbackAddNewRoute
  '/dashboard/projects/$view-id': typeof DashboardProjectsViewIdRoute
  '/dashboard/projects/add-new': typeof DashboardProjectsAddNewRoute
  '/dashboard/rapid-enquiry/$edit-id': typeof DashboardRapidEnquiryEditIdRoute
  '/dashboard/rapid-enquiry/add-new': typeof DashboardRapidEnquiryAddNewRoute
  '/dashboard/reporting/make-report': typeof DashboardReportingMakeReportRoute
  '/dashboard/reporting/review-report': typeof DashboardReportingReviewReportRoute
  '/dashboard/settings/add-role': typeof DashboardSettingsAddRoleRoute
  '/dashboard/stakeholders/$edit-id': typeof DashboardStakeholdersEditIdRoute
  '/dashboard/stakeholders/$view-id': typeof DashboardStakeholdersViewIdRoute
  '/dashboard/stakeholders/add-new': typeof DashboardStakeholdersAddNewRoute
  '/dashboard/surveys/$view-id': typeof DashboardSurveysViewIdRoute
  '/dashboard/surveys/add-new': typeof DashboardSurveysAddNewRoute
  '/dashboard/surveys/report-forms': typeof DashboardSurveysReportFormsRoute
  '/dashboard/surveys/review-survey': typeof DashboardSurveysReviewSurveyRoute
  '/dashboard/surveys/take-survey': typeof DashboardSurveysTakeSurveyRoute
  '/dashboard/surveys/thank-you': typeof DashboardSurveysThankYouRoute
  '/dashboard/accounts/': typeof DashboardAccountsIndexRoute
  '/dashboard/announcements/': typeof DashboardAnnouncementsIndexRoute
  '/dashboard/community-sessions/': typeof DashboardCommunitySessionsIndexRoute
  '/dashboard/docs/': typeof DashboardDocsIndexRoute
  '/dashboard/documents/': typeof DashboardDocumentsIndexRoute
  '/dashboard/feedback/': typeof DashboardFeedbackIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/rapid-enquiry/': typeof DashboardRapidEnquiryIndexRoute
  '/dashboard/reporting/': typeof DashboardReportingIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/stakeholders/': typeof DashboardStakeholdersIndexRoute
  '/dashboard/surveys/': typeof DashboardSurveysIndexRoute
  '/dashboard/feedback/edit/$edit-id': typeof DashboardFeedbackEditEditIdRoute
  '/dashboard/settings/edit-role/$roleId': typeof DashboardSettingsEditRoleRoleIdRoute
  '/dashboard/surveys/analytics/$survey-id': typeof DashboardSurveysAnalyticsSurveyIdRoute
  '/dashboard/surveys/answer/$survey-answer': typeof DashboardSurveysAnswerSurveyAnswerRoute
  '/dashboard/surveys/edit/$edit-id': typeof DashboardSurveysEditEditIdRoute
  '/dashboard/surveys/take/$survey-answer': typeof DashboardSurveysTakeSurveyAnswerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/posts'
    | '/approval-required'
    | '/error'
    | '/verify-organization'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/feedback/$programme'
    | '/posts/$postId'
    | '/dashboard/'
    | '/posts/'
    | '/dashboard/accounts/add-new'
    | '/dashboard/accounts/community-members'
    | '/dashboard/accounts/health-service-providers'
    | '/dashboard/accounts/rich-members'
    | '/dashboard/accounts/stakeholders'
    | '/dashboard/announcements/$edit-id'
    | '/dashboard/announcements/add-new'
    | '/dashboard/community-sessions/$sessionId'
    | '/dashboard/community-sessions/add-new'
    | '/dashboard/feedback/add-new'
    | '/dashboard/projects/$view-id'
    | '/dashboard/projects/add-new'
    | '/dashboard/rapid-enquiry/$edit-id'
    | '/dashboard/rapid-enquiry/add-new'
    | '/dashboard/reporting/make-report'
    | '/dashboard/reporting/review-report'
    | '/dashboard/settings/add-role'
    | '/dashboard/stakeholders/$edit-id'
    | '/dashboard/stakeholders/$view-id'
    | '/dashboard/stakeholders/add-new'
    | '/dashboard/surveys/$view-id'
    | '/dashboard/surveys/add-new'
    | '/dashboard/surveys/report-forms'
    | '/dashboard/surveys/review-survey'
    | '/dashboard/surveys/take-survey'
    | '/dashboard/surveys/thank-you'
    | '/dashboard/accounts'
    | '/dashboard/announcements'
    | '/dashboard/community-sessions'
    | '/dashboard/docs'
    | '/dashboard/documents'
    | '/dashboard/feedback'
    | '/dashboard/notifications'
    | '/dashboard/projects'
    | '/dashboard/rapid-enquiry'
    | '/dashboard/reporting'
    | '/dashboard/settings'
    | '/dashboard/stakeholders'
    | '/dashboard/surveys'
    | '/dashboard/feedback/edit/$edit-id'
    | '/dashboard/settings/edit-role/$roleId'
    | '/dashboard/surveys/analytics/$survey-id'
    | '/dashboard/surveys/answer/$survey-answer'
    | '/dashboard/surveys/edit/$edit-id'
    | '/dashboard/surveys/take/$survey-answer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approval-required'
    | '/error'
    | '/verify-organization'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/feedback/$programme'
    | '/posts/$postId'
    | '/dashboard'
    | '/posts'
    | '/dashboard/accounts/add-new'
    | '/dashboard/accounts/community-members'
    | '/dashboard/accounts/health-service-providers'
    | '/dashboard/accounts/rich-members'
    | '/dashboard/accounts/stakeholders'
    | '/dashboard/announcements/$edit-id'
    | '/dashboard/announcements/add-new'
    | '/dashboard/community-sessions/$sessionId'
    | '/dashboard/community-sessions/add-new'
    | '/dashboard/feedback/add-new'
    | '/dashboard/projects/$view-id'
    | '/dashboard/projects/add-new'
    | '/dashboard/rapid-enquiry/$edit-id'
    | '/dashboard/rapid-enquiry/add-new'
    | '/dashboard/reporting/make-report'
    | '/dashboard/reporting/review-report'
    | '/dashboard/settings/add-role'
    | '/dashboard/stakeholders/$edit-id'
    | '/dashboard/stakeholders/$view-id'
    | '/dashboard/stakeholders/add-new'
    | '/dashboard/surveys/$view-id'
    | '/dashboard/surveys/add-new'
    | '/dashboard/surveys/report-forms'
    | '/dashboard/surveys/review-survey'
    | '/dashboard/surveys/take-survey'
    | '/dashboard/surveys/thank-you'
    | '/dashboard/accounts'
    | '/dashboard/announcements'
    | '/dashboard/community-sessions'
    | '/dashboard/docs'
    | '/dashboard/documents'
    | '/dashboard/feedback'
    | '/dashboard/notifications'
    | '/dashboard/projects'
    | '/dashboard/rapid-enquiry'
    | '/dashboard/reporting'
    | '/dashboard/settings'
    | '/dashboard/stakeholders'
    | '/dashboard/surveys'
    | '/dashboard/feedback/edit/$edit-id'
    | '/dashboard/settings/edit-role/$roleId'
    | '/dashboard/surveys/analytics/$survey-id'
    | '/dashboard/surveys/answer/$survey-answer'
    | '/dashboard/surveys/edit/$edit-id'
    | '/dashboard/surveys/take/$survey-answer'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/posts'
    | '/approval-required'
    | '/error'
    | '/verify-organization'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/feedback/$programme'
    | '/posts/$postId'
    | '/dashboard/'
    | '/posts/'
    | '/dashboard/accounts/add-new'
    | '/dashboard/accounts/community-members'
    | '/dashboard/accounts/health-service-providers'
    | '/dashboard/accounts/rich-members'
    | '/dashboard/accounts/stakeholders'
    | '/dashboard/announcements/$edit-id'
    | '/dashboard/announcements/add-new'
    | '/dashboard/community-sessions/$sessionId'
    | '/dashboard/community-sessions/add-new'
    | '/dashboard/feedback/add-new'
    | '/dashboard/projects/$view-id'
    | '/dashboard/projects/add-new'
    | '/dashboard/rapid-enquiry/$edit-id'
    | '/dashboard/rapid-enquiry/add-new'
    | '/dashboard/reporting/make-report'
    | '/dashboard/reporting/review-report'
    | '/dashboard/settings/add-role'
    | '/dashboard/stakeholders/$edit-id'
    | '/dashboard/stakeholders/$view-id'
    | '/dashboard/stakeholders/add-new'
    | '/dashboard/surveys/$view-id'
    | '/dashboard/surveys/add-new'
    | '/dashboard/surveys/report-forms'
    | '/dashboard/surveys/review-survey'
    | '/dashboard/surveys/take-survey'
    | '/dashboard/surveys/thank-you'
    | '/dashboard/accounts/'
    | '/dashboard/announcements/'
    | '/dashboard/community-sessions/'
    | '/dashboard/docs/'
    | '/dashboard/documents/'
    | '/dashboard/feedback/'
    | '/dashboard/notifications/'
    | '/dashboard/projects/'
    | '/dashboard/rapid-enquiry/'
    | '/dashboard/reporting/'
    | '/dashboard/settings/'
    | '/dashboard/stakeholders/'
    | '/dashboard/surveys/'
    | '/dashboard/feedback/edit/$edit-id'
    | '/dashboard/settings/edit-role/$roleId'
    | '/dashboard/surveys/analytics/$survey-id'
    | '/dashboard/surveys/answer/$survey-answer'
    | '/dashboard/surveys/edit/$edit-id'
    | '/dashboard/surveys/take/$survey-answer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  ApprovalRequiredRoute: typeof ApprovalRequiredRoute
  ErrorRoute: typeof ErrorRoute
  VerifyOrganizationRoute: typeof VerifyOrganizationRoute
  FeedbackProgrammeRoute: typeof FeedbackProgrammeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-organization': {
      id: '/verify-organization'
      path: '/verify-organization'
      fullPath: '/verify-organization'
      preLoaderRoute: typeof VerifyOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-required': {
      id: '/approval-required'
      path: '/approval-required'
      fullPath: '/approval-required'
      preLoaderRoute: typeof ApprovalRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/feedback/$programme': {
      id: '/feedback/$programme'
      path: '/feedback/$programme'
      fullPath: '/feedback/$programme'
      preLoaderRoute: typeof FeedbackProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/surveys/': {
      id: '/dashboard/surveys/'
      path: '/surveys'
      fullPath: '/dashboard/surveys'
      preLoaderRoute: typeof DashboardSurveysIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/stakeholders/': {
      id: '/dashboard/stakeholders/'
      path: '/stakeholders'
      fullPath: '/dashboard/stakeholders'
      preLoaderRoute: typeof DashboardStakeholdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reporting/': {
      id: '/dashboard/reporting/'
      path: '/reporting'
      fullPath: '/dashboard/reporting'
      preLoaderRoute: typeof DashboardReportingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rapid-enquiry/': {
      id: '/dashboard/rapid-enquiry/'
      path: '/rapid-enquiry'
      fullPath: '/dashboard/rapid-enquiry'
      preLoaderRoute: typeof DashboardRapidEnquiryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/feedback/': {
      id: '/dashboard/feedback/'
      path: '/feedback'
      fullPath: '/dashboard/feedback'
      preLoaderRoute: typeof DashboardFeedbackIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/documents/': {
      id: '/dashboard/documents/'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/docs/': {
      id: '/dashboard/docs/'
      path: '/docs'
      fullPath: '/dashboard/docs'
      preLoaderRoute: typeof DashboardDocsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/community-sessions/': {
      id: '/dashboard/community-sessions/'
      path: '/community-sessions'
      fullPath: '/dashboard/community-sessions'
      preLoaderRoute: typeof DashboardCommunitySessionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/announcements/': {
      id: '/dashboard/announcements/'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/': {
      id: '/dashboard/accounts/'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/thank-you': {
      id: '/dashboard/surveys/thank-you'
      path: '/surveys/thank-you'
      fullPath: '/dashboard/surveys/thank-you'
      preLoaderRoute: typeof DashboardSurveysThankYouRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/take-survey': {
      id: '/dashboard/surveys/take-survey'
      path: '/surveys/take-survey'
      fullPath: '/dashboard/surveys/take-survey'
      preLoaderRoute: typeof DashboardSurveysTakeSurveyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/review-survey': {
      id: '/dashboard/surveys/review-survey'
      path: '/surveys/review-survey'
      fullPath: '/dashboard/surveys/review-survey'
      preLoaderRoute: typeof DashboardSurveysReviewSurveyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/report-forms': {
      id: '/dashboard/surveys/report-forms'
      path: '/surveys/report-forms'
      fullPath: '/dashboard/surveys/report-forms'
      preLoaderRoute: typeof DashboardSurveysReportFormsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/add-new': {
      id: '/dashboard/surveys/add-new'
      path: '/surveys/add-new'
      fullPath: '/dashboard/surveys/add-new'
      preLoaderRoute: typeof DashboardSurveysAddNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/$view-id': {
      id: '/dashboard/surveys/$view-id'
      path: '/surveys/$view-id'
      fullPath: '/dashboard/surveys/$view-id'
      preLoaderRoute: typeof DashboardSurveysViewIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/stakeholders/add-new': {
      id: '/dashboard/stakeholders/add-new'
      path: '/stakeholders/add-new'
      fullPath: '/dashboard/stakeholders/add-new'
      preLoaderRoute: typeof DashboardStakeholdersAddNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/stakeholders/$view-id': {
      id: '/dashboard/stakeholders/$view-id'
      path: '/stakeholders/$view-id'
      fullPath: '/dashboard/stakeholders/$view-id'
      preLoaderRoute: typeof DashboardStakeholdersViewIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/stakeholders/$edit-id': {
      id: '/dashboard/stakeholders/$edit-id'
      path: '/stakeholders/$edit-id'
      fullPath: '/dashboard/stakeholders/$edit-id'
      preLoaderRoute: typeof DashboardStakeholdersEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/add-role': {
      id: '/dashboard/settings/add-role'
      path: '/settings/add-role'
      fullPath: '/dashboard/settings/add-role'
      preLoaderRoute: typeof DashboardSettingsAddRoleRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reporting/review-report': {
      id: '/dashboard/reporting/review-report'
      path: '/reporting/review-report'
      fullPath: '/dashboard/reporting/review-report'
      preLoaderRoute: typeof DashboardReportingReviewReportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reporting/make-report': {
      id: '/dashboard/reporting/make-report'
      path: '/reporting/make-report'
      fullPath: '/dashboard/reporting/make-report'
      preLoaderRoute: typeof DashboardReportingMakeReportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rapid-enquiry/add-new': {
      id: '/dashboard/rapid-enquiry/add-new'
      path: '/rapid-enquiry/add-new'
      fullPath: '/dashboard/rapid-enquiry/add-new'
      preLoaderRoute: typeof DashboardRapidEnquiryAddNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rapid-enquiry/$edit-id': {
      id: '/dashboard/rapid-enquiry/$edit-id'
      path: '/rapid-enquiry/$edit-id'
      fullPath: '/dashboard/rapid-enquiry/$edit-id'
      preLoaderRoute: typeof DashboardRapidEnquiryEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/add-new': {
      id: '/dashboard/projects/add-new'
      path: '/projects/add-new'
      fullPath: '/dashboard/projects/add-new'
      preLoaderRoute: typeof DashboardProjectsAddNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/$view-id': {
      id: '/dashboard/projects/$view-id'
      path: '/projects/$view-id'
      fullPath: '/dashboard/projects/$view-id'
      preLoaderRoute: typeof DashboardProjectsViewIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/feedback/add-new': {
      id: '/dashboard/feedback/add-new'
      path: '/feedback/add-new'
      fullPath: '/dashboard/feedback/add-new'
      preLoaderRoute: typeof DashboardFeedbackAddNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/community-sessions/add-new': {
      id: '/dashboard/community-sessions/add-new'
      path: '/community-sessions/add-new'
      fullPath: '/dashboard/community-sessions/add-new'
      preLoaderRoute: typeof DashboardCommunitySessionsAddNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/community-sessions/$sessionId': {
      id: '/dashboard/community-sessions/$sessionId'
      path: '/community-sessions/$sessionId'
      fullPath: '/dashboard/community-sessions/$sessionId'
      preLoaderRoute: typeof DashboardCommunitySessionsSessionIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/announcements/add-new': {
      id: '/dashboard/announcements/add-new'
      path: '/announcements/add-new'
      fullPath: '/dashboard/announcements/add-new'
      preLoaderRoute: typeof DashboardAnnouncementsAddNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/announcements/$edit-id': {
      id: '/dashboard/announcements/$edit-id'
      path: '/announcements/$edit-id'
      fullPath: '/dashboard/announcements/$edit-id'
      preLoaderRoute: typeof DashboardAnnouncementsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/stakeholders': {
      id: '/dashboard/accounts/stakeholders'
      path: '/accounts/stakeholders'
      fullPath: '/dashboard/accounts/stakeholders'
      preLoaderRoute: typeof DashboardAccountsStakeholdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/rich-members': {
      id: '/dashboard/accounts/rich-members'
      path: '/accounts/rich-members'
      fullPath: '/dashboard/accounts/rich-members'
      preLoaderRoute: typeof DashboardAccountsRichMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/health-service-providers': {
      id: '/dashboard/accounts/health-service-providers'
      path: '/accounts/health-service-providers'
      fullPath: '/dashboard/accounts/health-service-providers'
      preLoaderRoute: typeof DashboardAccountsHealthServiceProvidersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/community-members': {
      id: '/dashboard/accounts/community-members'
      path: '/accounts/community-members'
      fullPath: '/dashboard/accounts/community-members'
      preLoaderRoute: typeof DashboardAccountsCommunityMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/add-new': {
      id: '/dashboard/accounts/add-new'
      path: '/accounts/add-new'
      fullPath: '/dashboard/accounts/add-new'
      preLoaderRoute: typeof DashboardAccountsAddNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/take/$survey-answer': {
      id: '/dashboard/surveys/take/$survey-answer'
      path: '/surveys/take/$survey-answer'
      fullPath: '/dashboard/surveys/take/$survey-answer'
      preLoaderRoute: typeof DashboardSurveysTakeSurveyAnswerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/edit/$edit-id': {
      id: '/dashboard/surveys/edit/$edit-id'
      path: '/surveys/edit/$edit-id'
      fullPath: '/dashboard/surveys/edit/$edit-id'
      preLoaderRoute: typeof DashboardSurveysEditEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/answer/$survey-answer': {
      id: '/dashboard/surveys/answer/$survey-answer'
      path: '/surveys/answer/$survey-answer'
      fullPath: '/dashboard/surveys/answer/$survey-answer'
      preLoaderRoute: typeof DashboardSurveysAnswerSurveyAnswerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/surveys/analytics/$survey-id': {
      id: '/dashboard/surveys/analytics/$survey-id'
      path: '/surveys/analytics/$survey-id'
      fullPath: '/dashboard/surveys/analytics/$survey-id'
      preLoaderRoute: typeof DashboardSurveysAnalyticsSurveyIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/edit-role/$roleId': {
      id: '/dashboard/settings/edit-role/$roleId'
      path: '/settings/edit-role/$roleId'
      fullPath: '/dashboard/settings/edit-role/$roleId'
      preLoaderRoute: typeof DashboardSettingsEditRoleRoleIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/feedback/edit/$edit-id': {
      id: '/dashboard/feedback/edit/$edit-id'
      path: '/feedback/edit/$edit-id'
      fullPath: '/dashboard/feedback/edit/$edit-id'
      preLoaderRoute: typeof DashboardFeedbackEditEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountsAddNewRoute: typeof DashboardAccountsAddNewRoute
  DashboardAccountsCommunityMembersRoute: typeof DashboardAccountsCommunityMembersRoute
  DashboardAccountsHealthServiceProvidersRoute: typeof DashboardAccountsHealthServiceProvidersRoute
  DashboardAccountsRichMembersRoute: typeof DashboardAccountsRichMembersRoute
  DashboardAccountsStakeholdersRoute: typeof DashboardAccountsStakeholdersRoute
  DashboardAnnouncementsEditIdRoute: typeof DashboardAnnouncementsEditIdRoute
  DashboardAnnouncementsAddNewRoute: typeof DashboardAnnouncementsAddNewRoute
  DashboardCommunitySessionsSessionIdRoute: typeof DashboardCommunitySessionsSessionIdRoute
  DashboardCommunitySessionsAddNewRoute: typeof DashboardCommunitySessionsAddNewRoute
  DashboardFeedbackAddNewRoute: typeof DashboardFeedbackAddNewRoute
  DashboardProjectsViewIdRoute: typeof DashboardProjectsViewIdRoute
  DashboardProjectsAddNewRoute: typeof DashboardProjectsAddNewRoute
  DashboardRapidEnquiryEditIdRoute: typeof DashboardRapidEnquiryEditIdRoute
  DashboardRapidEnquiryAddNewRoute: typeof DashboardRapidEnquiryAddNewRoute
  DashboardReportingMakeReportRoute: typeof DashboardReportingMakeReportRoute
  DashboardReportingReviewReportRoute: typeof DashboardReportingReviewReportRoute
  DashboardSettingsAddRoleRoute: typeof DashboardSettingsAddRoleRoute
  DashboardStakeholdersEditIdRoute: typeof DashboardStakeholdersEditIdRoute
  DashboardStakeholdersViewIdRoute: typeof DashboardStakeholdersViewIdRoute
  DashboardStakeholdersAddNewRoute: typeof DashboardStakeholdersAddNewRoute
  DashboardSurveysViewIdRoute: typeof DashboardSurveysViewIdRoute
  DashboardSurveysAddNewRoute: typeof DashboardSurveysAddNewRoute
  DashboardSurveysReportFormsRoute: typeof DashboardSurveysReportFormsRoute
  DashboardSurveysReviewSurveyRoute: typeof DashboardSurveysReviewSurveyRoute
  DashboardSurveysTakeSurveyRoute: typeof DashboardSurveysTakeSurveyRoute
  DashboardSurveysThankYouRoute: typeof DashboardSurveysThankYouRoute
  DashboardAccountsIndexRoute: typeof DashboardAccountsIndexRoute
  DashboardAnnouncementsIndexRoute: typeof DashboardAnnouncementsIndexRoute
  DashboardCommunitySessionsIndexRoute: typeof DashboardCommunitySessionsIndexRoute
  DashboardDocsIndexRoute: typeof DashboardDocsIndexRoute
  DashboardDocumentsIndexRoute: typeof DashboardDocumentsIndexRoute
  DashboardFeedbackIndexRoute: typeof DashboardFeedbackIndexRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardRapidEnquiryIndexRoute: typeof DashboardRapidEnquiryIndexRoute
  DashboardReportingIndexRoute: typeof DashboardReportingIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardStakeholdersIndexRoute: typeof DashboardStakeholdersIndexRoute
  DashboardSurveysIndexRoute: typeof DashboardSurveysIndexRoute
  DashboardFeedbackEditEditIdRoute: typeof DashboardFeedbackEditEditIdRoute
  DashboardSettingsEditRoleRoleIdRoute: typeof DashboardSettingsEditRoleRoleIdRoute
  DashboardSurveysAnalyticsSurveyIdRoute: typeof DashboardSurveysAnalyticsSurveyIdRoute
  DashboardSurveysAnswerSurveyAnswerRoute: typeof DashboardSurveysAnswerSurveyAnswerRoute
  DashboardSurveysEditEditIdRoute: typeof DashboardSurveysEditEditIdRoute
  DashboardSurveysTakeSurveyAnswerRoute: typeof DashboardSurveysTakeSurveyAnswerRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountsAddNewRoute: DashboardAccountsAddNewRoute,
  DashboardAccountsCommunityMembersRoute:
    DashboardAccountsCommunityMembersRoute,
  DashboardAccountsHealthServiceProvidersRoute:
    DashboardAccountsHealthServiceProvidersRoute,
  DashboardAccountsRichMembersRoute: DashboardAccountsRichMembersRoute,
  DashboardAccountsStakeholdersRoute: DashboardAccountsStakeholdersRoute,
  DashboardAnnouncementsEditIdRoute: DashboardAnnouncementsEditIdRoute,
  DashboardAnnouncementsAddNewRoute: DashboardAnnouncementsAddNewRoute,
  DashboardCommunitySessionsSessionIdRoute:
    DashboardCommunitySessionsSessionIdRoute,
  DashboardCommunitySessionsAddNewRoute: DashboardCommunitySessionsAddNewRoute,
  DashboardFeedbackAddNewRoute: DashboardFeedbackAddNewRoute,
  DashboardProjectsViewIdRoute: DashboardProjectsViewIdRoute,
  DashboardProjectsAddNewRoute: DashboardProjectsAddNewRoute,
  DashboardRapidEnquiryEditIdRoute: DashboardRapidEnquiryEditIdRoute,
  DashboardRapidEnquiryAddNewRoute: DashboardRapidEnquiryAddNewRoute,
  DashboardReportingMakeReportRoute: DashboardReportingMakeReportRoute,
  DashboardReportingReviewReportRoute: DashboardReportingReviewReportRoute,
  DashboardSettingsAddRoleRoute: DashboardSettingsAddRoleRoute,
  DashboardStakeholdersEditIdRoute: DashboardStakeholdersEditIdRoute,
  DashboardStakeholdersViewIdRoute: DashboardStakeholdersViewIdRoute,
  DashboardStakeholdersAddNewRoute: DashboardStakeholdersAddNewRoute,
  DashboardSurveysViewIdRoute: DashboardSurveysViewIdRoute,
  DashboardSurveysAddNewRoute: DashboardSurveysAddNewRoute,
  DashboardSurveysReportFormsRoute: DashboardSurveysReportFormsRoute,
  DashboardSurveysReviewSurveyRoute: DashboardSurveysReviewSurveyRoute,
  DashboardSurveysTakeSurveyRoute: DashboardSurveysTakeSurveyRoute,
  DashboardSurveysThankYouRoute: DashboardSurveysThankYouRoute,
  DashboardAccountsIndexRoute: DashboardAccountsIndexRoute,
  DashboardAnnouncementsIndexRoute: DashboardAnnouncementsIndexRoute,
  DashboardCommunitySessionsIndexRoute: DashboardCommunitySessionsIndexRoute,
  DashboardDocsIndexRoute: DashboardDocsIndexRoute,
  DashboardDocumentsIndexRoute: DashboardDocumentsIndexRoute,
  DashboardFeedbackIndexRoute: DashboardFeedbackIndexRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardRapidEnquiryIndexRoute: DashboardRapidEnquiryIndexRoute,
  DashboardReportingIndexRoute: DashboardReportingIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardStakeholdersIndexRoute: DashboardStakeholdersIndexRoute,
  DashboardSurveysIndexRoute: DashboardSurveysIndexRoute,
  DashboardFeedbackEditEditIdRoute: DashboardFeedbackEditEditIdRoute,
  DashboardSettingsEditRoleRoleIdRoute: DashboardSettingsEditRoleRoleIdRoute,
  DashboardSurveysAnalyticsSurveyIdRoute:
    DashboardSurveysAnalyticsSurveyIdRoute,
  DashboardSurveysAnswerSurveyAnswerRoute:
    DashboardSurveysAnswerSurveyAnswerRoute,
  DashboardSurveysEditEditIdRoute: DashboardSurveysEditEditIdRoute,
  DashboardSurveysTakeSurveyAnswerRoute: DashboardSurveysTakeSurveyAnswerRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  ApprovalRequiredRoute: ApprovalRequiredRoute,
  ErrorRoute: ErrorRoute,
  VerifyOrganizationRoute: VerifyOrganizationRoute,
  FeedbackProgrammeRoute: FeedbackProgrammeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
